### ISSUE TITLE
Invalid status 6814 (Unknown reason)

### ISSUE THREAD

**Issue by philhp** [Zondax/ledger-kusama#199]
Hello,

I have a Ledger nano X

I would like to make upgrade ( because into Ledger Live still used old version v20.9391 )

when I download the GitHub release, I have this error :

Generated random root public key : b'048a866cd5a067d9595352e3ad8ec1190dda41e73db093524c515105fbdbfda26cc898b9e3abb732e485f8a027a557201797e7a9ba6aaab4cea1f12349ff4fb0f7'
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/philippededieu/Library/Python/3.9/lib/python/site-packages/ledgerblue/loadApp.py", line 175, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/Users/philippededieu/Library/Python/3.9/lib/python/site-packages/ledgerblue/deployed.py", line 88, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/Users/philippededieu/Library/Python/3.9/lib/python/site-packages/ledgerblue/comm.py", line 157, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6814 (Unknown reason)

Thanks in advance for tour help.

:link: [zboto Link](https://app.clickup.com/t/86782te98)

**Comment by philhp** [comment]
When i run the old version v20.9391 on my Ledger nano X  :

$ ./installer_nanos_xl.sh load
Generated random root public key : b'0407ed567d7d96762196db0933175d6811cfff775b799f11eafc280004a7bb1dbca08e2cb943f7cff00a7924bb30813b2b5d302d71f8f40fdcebe562e8c3df13c0'
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/philippededieu/Library/Python/3.9/lib/python/site-packages/ledgerblue/loadApp.py", line 175, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/Users/philippededieu/Library/Python/3.9/lib/python/site-packages/ledgerblue/deployed.py", line 88, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/Users/philippededieu/Library/Python/3.9/lib/python/site-packages/ledgerblue/comm.py", line 157, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6e00 (Unexpected state of device: verify that the right application is opened?)

( Ledger Live is not running when I launch this command )

**Comment by carlosala** [comment]
Hi @philhp!
You cannot sideload non-official versions of apps in Ledger Nano X, it's a limitation that other devices do not have.
In order to update the app (which has already been released in Ledger Live), make sure you have the latest firmware and you'll see the upgrade.
Thanks for the report!
